# Generated by Django 3.1.5 on 2021-01-14 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_course_created_at'),
        ('Courses_Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='related_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Courses.course', verbose_name='Related Course'),
            preserve_default=False,
        ),
    ]
