# Generated by Django 3.1.5 on 2021-01-12 02:03

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_full_name', models.CharField(max_length=750, verbose_name="User's Full Name")),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name="User's Email Address")),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='Account Activated')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', Accounts.models.UserManager()),
            ],
        ),
    ]
