# Generated by Django 3.1.5 on 2021-01-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile_pic',
            field=models.ImageField(default='/styling/assets/images/avatars/avatar-3.jpg', upload_to='Users_Profile_Pics'),
        ),
    ]
