# Generated by Django 3.1.5 on 2021-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_pic',
            field=models.ImageField(default='https://www.gravatar.com/avatar/94d093eda664addd6e450d7e9881bcad?s=32&d=identicon&r=PG', upload_to='Users_Profile_Pics'),
        ),
    ]
