# Generated by Django 3.1.5 on 2021-01-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_user_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_pic',
            field=models.ImageField(default='/styling/assets/images/avatar.png', upload_to='Users_Profile_Pics'),
        ),
    ]
