# Generated by Django 3.1.5 on 2021-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_course_created_at'),
        ('Accounts', '0006_auto_20210113_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_on_going_courses',
            field=models.ManyToManyField(to='Courses.Course', verbose_name="User's on going courses"),
        ),
    ]
