# Generated by Django 3.1.5 on 2021-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Accounts', '0008_auto_20210113_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_subjects',
            field=models.ManyToManyField(blank=True, to='Subjects.Subject', verbose_name="Users' Selected Subjects"),
        ),
    ]
