# Generated by Django 3.1.4 on 2021-01-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body_as_text', models.TextField(verbose_name='Question body as a text')),
                ('question_body_as_image', models.ImageField(upload_to='', verbose_name='Question body as an image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_duration', models.CharField(max_length=300, verbose_name='Quiz duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_questions', models.ManyToManyField(to='Quizes.Question', verbose_name='Related quetions')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_as_text', models.TextField(verbose_name='Answer as a text')),
                ('answer_as_img', models.ImageField(upload_to='', verbose_name='Answer as an image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizes.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
