# Generated by Django 3.1.4 on 2021-01-11 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
        ('Quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='related_subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Subjects.subject', verbose_name='Related subject'),
            preserve_default=False,
        ),
    ]
