# Generated by Django 3.1.5 on 2021-01-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_View', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
