# Generated by Django 3.1.7 on 2021-03-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_View', '0004_beststudent_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='related_teacher_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Accounts.user', verbose_name='Related Teacher Account'),
            preserve_default=False,
        ),
    ]
