# Generated by Django 3.1.6 on 2021-02-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_View', '0004_beststudent_staffmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='teacher_pic',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='staff_member_pic',
            field=models.ImageField(default='member_photo.png', upload_to='Staff_Members_Photos', verbose_name='Staff Member Picture'),
            preserve_default=False,
        ),
    ]
