# Generated by Django 3.1.7 on 2021-03-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_View', '0005_staffmember_related_teacher_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='related_teacher_account',
        ),
    ]
