# Generated by Django 3.1.4 on 2021-01-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=300, verbose_name='Lesson Name')),
                ('lesson_video_file', models.FileField(null=True, upload_to='', verbose_name='Lesson Video File')),
                ('lesson_video_link', models.CharField(max_length=700, null=True, verbose_name='Lesson Video Link')),
            ],
            options={
                'verbose_name': 'Course Lesson',
                'verbose_name_plural': 'Course Lessons',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=300, verbose_name='Course Name')),
                ('attached_PDF', models.FileField(null=True, upload_to='', verbose_name='Attach PDF')),
                ('course_content', models.ManyToManyField(to='Courses.CourseLesson', verbose_name="Course's Content")),
                ('related_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.coursecategory', verbose_name='Related Category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
