# Generated by Django 3.1.5 on 2021-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name_as_slug',
            field=models.SlugField(default='slug-here', max_length=350, verbose_name='Course Name as Slug'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='category_name_as_slug',
            field=models.SlugField(default='slug-here', max_length=350, verbose_name='Category Name as Slug'),
        ),
    ]
