# Generated by Django 3.1.5 on 2021-01-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_auto_20210112_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='lesson_video_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Lesson Video File'),
        ),
    ]
