# Generated by Django 3.1.5 on 2021-01-12 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_auto_20210112_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Added at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='lesson_video_file',
            field=models.FileField(blank=True, null=True, upload_to='Courses_Contents', verbose_name='Lesson Video File'),
        ),
    ]
