# Generated by Django 3.1.5 on 2021-01-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_auto_20210112_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attached_PDF',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attach PDF'),
        ),
    ]
