# Generated by Django 3.1.5 on 2021-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_auto_20210112_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_thumbnail',
            field=models.ImageField(default='course-thumbnail.png', upload_to='Courses_Thumbnails', verbose_name="Course's Thumbnail"),
        ),
    ]
