# Generated by Django 3.1.5 on 2021-01-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_course_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_trailer_video',
            field=models.FileField(default='course-trailer.mp4', upload_to='Courses_Trailers', verbose_name="Course's Trailer Video"),
        ),
    ]
