# Generated by Django 3.1.6 on 2021-02-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Educational_Stages', '0001_initial'),
        ('Courses', '0010_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='related_category',
        ),
        migrations.AddField(
            model_name='course',
            name='related_subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Educational_Stages.subject', verbose_name='Related Subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
