# Generated by Django 3.1.7 on 2021-03-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_auto_20210311_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_content',
        ),
        migrations.AddField(
            model_name='courselesson',
            name='related_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Courses.course', verbose_name='Related Course'),
            preserve_default=False,
        ),
    ]
