# Generated by Django 3.1.7 on 2021-03-25 09:19

import admin_resumable.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_auto_20210311_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='lesson_video_file',
            field=admin_resumable.fields.ModelAdminResumableFileField(default='lesson.mp4', upload_to='unused'),
            preserve_default=False,
        ),
    ]
