# Generated by Django 3.1.6 on 2021-02-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationlStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_stage_name', models.CharField(max_length=300, verbose_name='Educational stage name')),
                ('edu_stage_name_as_slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Educational Stage',
                'verbose_name_plural': 'Educational Stages',
            },
        ),
        migrations.CreateModel(
            name='EducationStageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_stage_level', models.CharField(max_length=350, verbose_name='Educational Stage Level')),
                ('created_At', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_edu_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Educational_Stages.educationlstage', verbose_name='Related Edu Stage')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=350, verbose_name='Subject Name')),
                ('semester', models.CharField(max_length=350, verbose_name='Semester')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('related_edu_stage_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Educational_Stages.educationstagelevel', verbose_name='Related Edu Stage Level')),
            ],
        ),
    ]
