# Generated by Django 3.1.6 on 2021-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educational_Stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlstage',
            name='edu_stage_name_as_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Keep it empty'),
        ),
    ]
