# Generated by Django 3.1.6 on 2021-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educational_Stages', '0002_auto_20210207_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationstagelevel',
            name='edu_stage_level_as_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Keep It empty'),
        ),
    ]
