# Generated by Django 3.1.6 on 2021-02-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educational_Stages', '0003_educationstagelevel_edu_stage_level_as_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_thumbnail',
            field=models.ImageField(default='subject-thumbnail.png', upload_to='Subjects_Thumbnails', verbose_name="Subject's Thumbnail"),
        ),
    ]
